language: node_js
notifications:
  email: false
node_js: 12
addons:
  ssh_known_hosts: sus.picio.us
before_deploy:
  - openssl aes-256-cbc -K $encrypted_3342d839e2e4_key -iv $encrypted_3342d839e2e4_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script:
    ssh deploy@sus.picio.us "bash -c rm -rf /var/sus.picio.us/html/*"; rsync
    -r --delete-after --quiet $TRAVIS_BUILD_DIR/build deploy@sus.picio.us:/var/sus.picio.us/html/
  on:
    branch: main
env:
  global:
    - secure: aJ6zDayjZO9Z1GvEFA3k2ApgwNgNGwFSmt7Z9zYjlojkIFA5RiCMlRUSXVExkjjwx55F5lY5WsuOw9m+HFdaG+m8Xoe6OJSfcrJDrH/dey6BQbQqN4FUmtg/2XSqtbevmHgedKbDjVUZUuFIwQppg6p1BC25zKjT6JtxhOLuLSTov1AC6kEw/CdMn49n6jq8CzmHhuw1lRCyW1JkKhxg+F7vatvt9qICuuntD/qndcWQv4jWkQrNIg3ON+VLkn2DjFjk/73dB4pG1+E3oQI8tzI6bOVHn/9fAL/Wwv3SGpXyBaylredn63cBBi5XvcvnQ9o+fqoE1UtBQiqqwVkZjhCOY+YGww8thuhGyV+054Lga/EuU0kE64XoP934plZfVhabF7mUkxbPYkDpRcrIrk8Zg6FNVAmJi7RvyeYKjucpZDQ7y/j8vjsfw2nrCEDOV4ApbHJIOl1+FuQiBzoqyh4Ds/WVlyXJYb76nC3G1SzqMaACzNp6wM25AibxxEyEyT3BD3QaJkwO/muH8FvVDFtdTNLfJmeFYcIulHhj5RT5DyIgqGMvDqTi4eh7rrDSTPFIJdSDpjAiV9iqst1R832JyXm3dYGplbBlIcTsoLBfRA6GWrWdUfyGb7Ffu/s9zWZlwO3yLgFzMU6J1IZd1w45f5TJOOpnTYFWgC93cSM=
    - secure: gcXV9yi/rhSWfiYhhefDuMA1b3YquHs27aVbY9VPqkopNB95zeXLVM0ZYOQrSZniK4O8hlZtEdPRfwWLm6qsHaz3qwofy+d+pStC1QB/bg4k7AB0ORm2uOwD42EKxYpR40HNzlbB5hNCGfAHaKjwk059wbvWT/6jK/tXSJnG4y+L+zCCWKrF4ZyddsaSq1mui51dFsyzOdw4A9WxT/yHo5C2z+DGNaoNgDQNUfHVuzfQs1pJ0Kzq51U25hoAARhj30i/rf0ZckK+hlsdqoToeWBi4vfVldWFdlhBAOP/BlgfV0l/qNuIccR9xkndJ/BjNbRYoeIS/bxlbJuypRJNZ9efmOV2BpPtIA6IVG4sDq8GcgLtmrXYY1DE0roR91aMGcvwdUMr9Hdhv0/vcUsDhxvXv05mdzYnDW1046U/4QvYkRqSWxRSeb4mc8Ft8RL+l1YF4hbxSCf+3CexH8RBOK6eMlifAsOTmshyPHvBbgqn08Mp/Ix0BkuRSwwAcGOBJu9kiFzgl3qonDNA+f1GSmWxvfSV/Qik6JsR+bBSOTT76cYqPQQiwsLKGFriGDJzx1yKZ0rJvGkT6OPpzIRj6Kyk4Krz0YLt82VdjhA5eLuwtvQdHQyYSrs3fXCM5IDyrgZMWAOdm6VHLS9fn2/cci4OIp9uy7OMtJLzeCqkN9A=
